apiVersion: v1
kind: Service
metadata:
  name: postgresql-proxy-service
  namespace: system-apps
  labels:
    app: postgresql-proxy
spec:
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: pgsql
  selector:
    app: postgresql-proxy
