apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: system-apps
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "<MYSQL_ROOT_PASSWORD>"
  MYSQL_DATABASE: "deployra"
  MYSQL_USER: "deployra"
  MYSQL_PASSWORD: "<MYSQL_PASSWORD>"
