apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: system-apps
  labels:
    app: redis
    managedBy: kubestrator
    type: redis
    project: system
    service: redis
    username-1: deployra
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
    name: port-0
  clusterIP: None
