apiVersion: v1
kind: Service
metadata:
  name: memory-proxy-service
  namespace: system-apps
  labels:
    app: memory-proxy
spec:
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: memory
  selector:
    app: memory-proxy
