apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubestrator-sa
  namespace: system-apps
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubestrator-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "services", "namespaces", "secrets", "configmaps", "persistentvolumeclaims", "persistentvolumes"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses", "networkpolicies"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubestrator-role-binding
subjects:
- kind: ServiceAccount
  name: kubestrator-sa
  namespace: system-apps
roleRef:
  kind: ClusterRole
  name: kubestrator-role
  apiGroup: rbac.authorization.k8s.io