apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-proxy-sa
  namespace: system-apps
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysql-proxy-role
rules:
- apiGroups: [""]
  resources: ["services", "configmaps", "namespaces"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mysql-proxy-role-binding
subjects:
- kind: ServiceAccount
  name: mysql-proxy-sa
  namespace: system-apps
roleRef:
  kind: ClusterRole
  name: mysql-proxy-role
  apiGroup: rbac.authorization.k8s.io
