apiVersion: v1
kind: Service
metadata:
  name: mysql-proxy-service
  namespace: system-apps
  labels:
    app: mysql-proxy
spec:
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
    name: mysql
  selector:
    app: mysql-proxy
