apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-proxy-sa
  namespace: system-apps
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: web-proxy-role
rules:
- apiGroups: [""]
  resources: ["services", "configmaps", "namespaces", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: web-proxy-role-binding
subjects:
- kind: ServiceAccount
  name: web-proxy-sa
  namespace: system-apps
roleRef:
  kind: ClusterRole
  name: web-proxy-role
  apiGroup: rbac.authorization.k8s.io
